feat: adding API's tagert_lin_uri and user to launch lti
oat-sa/e2e-runner pull request #20
Opened 2021-08-13 07:17 UTC by Dang3rZone

**Related to:** https://oat-sa.atlassian.net/browse/PR-489

**Description:** Need to update `getLtiLaunchUrl` cypress command to use API's full capability for authorizing a test as a proctor, choose a custom user and launch link:

**See** https://oat-sa.atlassian.net/browse/TR-963
[x] Session control / auto authorize / the proctoring tool should automatically authorize the test-sessions

2021-08-16 07:50 UTC, adriloma requested changes
Works good, tested on proctoring: already working tests still pass, and using new properties also do.

Can you update the name of the PR to something more precise? Be careful when choosing branch and PR names as current ones are too general and imprecise names. Also, as this was handled outside of PR-489 scope, it would need its own ticket (and branch name should had refference to the new ticket).


- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following conventional commits
- [x] Commits messages are meaningful
- [x] Commits are atomic

2021-08-16 09:39 UTC, adriloma approved these changes

2021-08-23 07:37 UTC, andrey-ponamarev commented on support/lti.js
> +    const { toolUrl, authToken, registration, targetLink, user } = options;
Could you add an example to the JSDoc comments above?

2021-08-23 07:38 UTC, andrey-ponamarev approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`
- [x] Pull request title and description are meaningful
- [x] Commits are following conventional commits

2021-08-23 08:47 UTC, yukipastelcat approved these changes
All good, +1 on adding the example of `'getLtiLaunchUrl'` command to docs👍

- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following conventional commits
- [x] Commits messages are meaningful
- [x] Commits are atomic

2021-08-23 09:52 UTC, merged